// Manchester venues — shared data
window.MCR_VENUES = [
  { n: 1,  name: "The Refuge",            cat: "fancy",    area: "Oxford Road",        x: 53.97, y: 74.71, ig: "therefugemcr", blurb: "Huge tiled hotel bar opposite Oxford Road station. Go for the room as much as the drink. The Kimpton Clocktower one — old Principal Hotel.", tip: "First-night spot. Old Manchester money meets media agency expense account." },
  { n: 2,  name: "20 Stories",            cat: "fancy",    area: "Spinningfields",     x: 29.17, y: 50.9, ig: "20storiesmcr", blurb: "Rooftop cocktails, skyline views. Bit flashy and influencer-heavy but absolutely worth it at sunset.", tip: "Book ahead. Go for sunset, leave before the bottle service crowd." },
  { n: 3,  name: "The Ivy",               cat: "fancy",    area: "Spinningfields",     x: 29.94, y: 51.31, ig: "the_ivy_collection", blurb: "Brasserie on Spinningfields in the old Manchester House. Green-and-brass interior, terrace, all-day. Polished, accessible posh — a good treat-your-cousin spot.", tip: "Book ahead. Sit on the terrace if it's dry." },
  { n: 4,  name: "Peveril of the Peak",   cat: "pub",      area: "Near Northern Quarter", x: 40.42, y: 66.64, ig: "", blurb: "Tiny green-tiled Victorian pub. Looks like it hasn't changed in 100 years — thankfully. No music, no nonsense.", tip: "Old man pub. Just how it should be." },
  { n: 5,  name: "The Lass O'Gowrie",     cat: "pub",      area: "Charles Street",     x: 53.2, y: 67.85, ig: "thelassogowriemcr", blurb: "Tiny traditional boozer. Student / indie / old man pub all at once. Usually busy. Great pints, zero frills.", tip: "Cash friendly. Perfectly fine on your own." },
  { n: 6,  name: "The Castle Hotel",      cat: "pub",      area: "Oldham Street, NQ",  x: 65.47, y: 34.36, ig: "thecastlemanc", blurb: "Tiny Northern Quarter pub. Robinsons cask, sticky floors, tiny gig room out the back. Always a mixed crowd.", tip: "Exactly what you want a pub to be." },
  { n: 7,  name: "The Marble Arch",       cat: "pub",      area: "Rochdale Rd",        x: 67.26, y: 6.52, ig: "themarblearchmcr", blurb: "Iconic wet-led pub a bit north of the centre. Famous Victorian tiled interior. Owned by Marble Brewery — proper beer.", tip: "Worth the walk. Old industrial Manchester energy." },
  { n: 8,  name: "The Britons Protection", cat: "pub",     area: "50 Great Bridgewater St", x: 39.4, y: 65.03, ig: "thebritonsprotection", blurb: "Listed Victorian boozer near Bridgewater Hall. Tiled corridors, whisky list a mile long, proper old-school. The bathrooms haven't been touched since the 1930s.", tip: "If they like old-school pubs, take them here. Original Manchester." },
  { n: 9,  name: "The Gas Lamp",          cat: "pub",      area: "50a Bridge St",      x: 34.54, y: 43.24, ig: "thegaslampmcr", blurb: "Hidden underground bar opposite Crazy Pedro's. Victorian tiles, gaslight-era fittings, whisky-heavy, properly atmospheric. You'd walk past it.", tip: "One of the best bars in Manchester. Go down the stairs." },
  { n: 10, name: "Sinclair's Oyster Bar", cat: "pub",      area: "Shambles Sq, by the Cathedral", x: 44, y: 27.9, ig: "", blurb: "Cheapest pints in Manchester. 16th-century timber-framed pub, picked up and moved when the Arndale was built in the 70s, then moved AGAIN after the '96 IRA bomb. Sam Smith's prices that haven't caught up with the century.", tip: "Sit in the courtyard with a £2-something pint. Two of the oldest buildings in the city, both relocated twice." },
  { n: 11, name: "The Old Wellington",    cat: "pub",      area: "Shambles Sq, by the Cathedral", x: 44, y: 27.5, ig: "oldwellington", blurb: "Half-timbered black-and-white pub next to Sinclair's. Same story — moved during the Arndale build, moved again after the 1996 bomb. Greene King now but the building is the point.", tip: "Pair with Sinclair's. Two pints, two centuries of history, ten quid." },
  { n: 12, name: "Temple Bar",            cat: "dive",     area: "Oxford Rd",          x: 54.99, y: 74.71, ig: "", blurb: "Underground dive bar in a converted public toilet. Sticky floors, loud music, almost no seating. Very Manchester.", tip: "Caveat: it's small, grimy, definitely a dive. If you hate cramped, skip it." },
  { n: 13, name: "Big Hands",             cat: "dive",     area: "New Wakefield St",   x: 49.11, y: 76.73, ig: "bighandsbar", blurb: "Grungy, cheap, open late. Sticky floors, posters everywhere, strong drinks. Like a uni bar that survived into adulthood.", tip: "Still looks like tetanus in bar form. Still excellent." },
  { n: 14, name: "YES",                   cat: "music",     area: "Charles Street",     x: 58.83, y: 65.83, ig: "yes_mcr", blurb: "Four floors. Bar, gigs, DJs, rooftop terrace. Starts civilised, ends in techno. Important modern Manchester venue.", tip: "Roof terrace if the weather's good. Stays open late." },
  { n: 15, name: "The Molly House",       cat: "modern",     area: "Richmond St, Gay Village", x: 63.43, y: 60.18, ig: "themollyhousemanchester", blurb: "Two-floor Victorian-parlour bar in the Gay Village. Gin list, cocktails, Spanish-ish small plates. Civilised, slightly camp, properly good. Not a club — somewhere to actually talk.", tip: "Right between the NQ and YES. Perfect mid-evening stop." },
  { n: 16, name: "Common",                cat: "modern",     area: "39-41 Edge St, NQ",  x: 63.43, y: 32.34, ig: "common_bar", blurb: "NQ bar that changes its mural every year. Pinball, decent burgers, late nights. The most NQ bar in the NQ.", tip: "Solid late-evening stop." },
  { n: 17, name: "Albert Schloss",        cat: "modern",    area: "Peter St",           x: 39.65, y: 59.38, ig: "albertsschloss", blurb: "Bavarian-style bier palace under the prestigious Albert Hall — old Wesleyan chapel turned gig venue upstairs. Schloss is the bar; loud, theatrical, late. Lederhosen, pretzels, live music nightly.", tip: "If you can catch a gig in the Albert Hall above, do it. The room is ridiculous. Schloss is the warm-up." },
  { n: 18, name: "Band on the Wall",      cat: "music",    area: "Swan St, NQ",        x: 70.59, y: 27.5, ig: "bandonthewall", blurb: "Manchester music institution. Jazz, soul, electronic, world music, indie — they book everything.", tip: "Tied to Manchester's music history. Always worth checking listings." },
  { n: 19, name: "Freight Island",        cat: "music",    area: "Baring St, Mayfield", x: 84.39, y: 72.69, ig: "freightislandmcr", blurb: "Massive food, drink and events space neighbouring The Warehouse Project — same Mayfield Depot site, same industrial-apocalypse scale. Old railway depot turned nightlife.", tip: "Easy spot for a group with mixed tastes. If WHP is on, the whole site is alive." },
  { n: 20, name: "Cloudwater",            cat: "brewery",  area: "Unit 9, Piccadilly Trading Estate", x: 74.93, y: 79.96, ig: "cloudwaterbrew", blurb: "Manchester's most internationally respected modern brewery. Industrial taproom. Serious craft beer crowd.", tip: "If beer matters to you, this is the one." },
  { n: 21, name: "Track Brewing",         cat: "brewery",  area: "Unit 18, Piccadilly Trading Estate", x: 79.79, y: 75.92, ig: "trackbrewingco", blurb: "Huge modern taproom in the Piccadilly Trading Estate. Industrial estate location sounds awful but works perfectly.", tip: "Very 'new Manchester'. Go on a sunny afternoon." },
  { n: 22, name: "Port Street Beer House", cat: "pub",     area: "39-41 Port St, NQ",  x: 68.54, y: 33.96, ig: "portstreetbeer", blurb: "NQ bar with the most serious beer list in town. Cask, craft, bottle list a mile long, two floors, no music, no nonsense.", tip: "Great between Mackie Mayor and The Castle." },
  { n: 23, name: "Hatch",                 cat: "food",     area: "103 Oxford Rd",      x: 67.01, y: 93.68, ig: "hatchmcr", blurb: "Shipping-container food and drink spot under the Mancunian Way. Students, dogs, chaos. Good reputation.", tip: "Easy, cheap, casual. Good for a quick stop." },
  { n: 24, name: "Rudy's Pizza — Ancoats", cat: "food",    area: "9 Cotton St, Ancoats", x: 78.77, y: 29.52, ig: "wearerudyspizza", blurb: "The original Rudy's. Proper Neapolitan pizza. Simple as that.", tip: "Go here over the newer sites. Original always wins." },
  { n: 25, name: "Bundobust",             cat: "food",     area: "Piccadilly",         x: 61.64, y: 53.73, ig: "bundobust", blurb: "Indian street food + craft beer. More casual, more independent than Dishoom. Get the okra fries.", tip: "Like Dishoom got taken over by craft beer nerds and indie music people." },
  { n: 26, name: "Mackie Mayor",          cat: "food",     area: "Eagle St, NQ",       x: 66.75, y: 25.89, ig: "mackiemayor", blurb: "Beautiful old market building turned food hall. Multiple vendors, communal seating.", tip: "Best when no one can decide what to eat. Always packed." },
  { n: 27, name: "Dishoom",               cat: "food",     area: "Spinningfields",     x: 25.59, y: 45.25, ig: "dishoom", blurb: "Polished Bombay-inspired restaurant. Touristy now but still good. The bacon naan at breakfast is borderline mandatory.", tip: "No Dishoom in Dublin — worth trying if you haven't been. Get a booking." },
  { n: 29, name: "TAKK",                  cat: "coffee",   area: "59 Stevenson Square", x: 65.47, y: 37.18, ig: "takkmcr", blurb: "Icelandic-inspired Northern Quarter coffee institution. Peak 'creative Manchester circa 2015' energy.", tip: "Still feels right. Good for a slow morning." },
  { n: 30, name: "Pot Kettle Black",      cat: "coffee",   area: "14 Barton Arcade",   x: 45.02, y: 34.76, ig: "pkb_mcr", blurb: "Consistently excellent coffee inside one of the prettiest arcades in the city. One of the best.", tip: "Worth visiting just for the arcade itself." },
  { n: 31, name: "Pollen Bakery",         cat: "coffee",   area: "113-115 Cutting Room Sq, Ancoats", x: 80.81, y: 29.92, ig: "pollenbakery", blurb: "Excellent pastries, sourdough and coffee by the canal in Ancoats.", tip: "Slow Sunday morning. Sit by the water." },
  { n: 32, name: "Affleck's",             cat: "culture",  area: "Tib St / Church St, NQ", x: 63.43, y: 39.2, ig: "afflecks_manchester", blurb: "Indoor market of indie shops, vintage clothes, piercers, record stalls and weird tat. Has been there since the 80s. Manchester in a building.", tip: "Get lost in it for an hour. Don't buy anything you don't need." },
  { n: 33, name: "Piccadilly Records",    cat: "culture",  area: "53 Oldham St, NQ",   x: 64.45, y: 37.99, ig: "piccadillyrecords", blurb: "One of the best independent record shops in the country. The staff actually know what they're talking about.", tip: "Even if you don't buy vinyl, the recommendation walls are worth a look." },
  { n: 34, name: "Projekts MCR",          cat: "daytime",  area: "Mancunian Way flyover, Hulme", x: 39.65, y: 93.68, ig: "projektsmcr", blurb: "Outdoor skatepark tucked under the Mancunian Way flyover by Hulme Park. Concrete, graffiti, kids on boards. Very Manchester.", tip: "Where Mind Enterprise are playing. Walkable from Hatch." },
  { n: 35, name: "John Rylands Library",  cat: "daytime",  area: "150 Deansgate",      x: 36.59, y: 52.92, ig: "thejohnrylands", blurb: "Neo-gothic library that looks like a cathedral. Free, you can just walk in. Reading room is one of the most beautiful rooms in the city.", tip: "The one you actually need to see. Quiet hour or two on a Saturday morning." },
  { n: 36, name: "Central Library",       cat: "daytime",  area: "St Peter's Square",  x: 43.49, y: 57.76, ig: "manchester-central-library", igUrl: "https://www.instagram.com/explore/locations/495483728/manchester-central-library/", blurb: "Circular Pantheon-style building with a domed reading room upstairs. Free, public, gorgeous.", tip: "Sit in the Wolfson Reading Room for ten minutes. It's free and it's stunning." },
  { n: 37, name: "Chetham's Library",     cat: "daytime",  area: "Long Millgate, Cathedral Quarter", x: 45.28, y: 24.27, ig: "chethamslibrary", blurb: "Oldest free public library in the English-speaking world (1653). Marx and Engels worked here — the desk is still there. Tudor building, not many people know about it.", tip: "Book ahead — guided tours only. Hidden behind Chetham's School of Music." },
  { n: 38, name: "Manchester Cathedral",  cat: "daytime",  area: "Victoria St",        x: 44.0, y: 27.5, ig: "manchestercathedral", blurb: "15th-century gothic cathedral. Small but old. Bombed in WWII, again in 1996. Free to wander.", tip: "Right next to Sinclair's. Pop in, have a look, get a pint after." },
  { n: 39, name: "Manchester Art Gallery",cat: "daytime",  area: "Mosley St",          x: 51.16, y: 50.9, ig: "mcrartgallery", blurb: "City's main gallery. Strong Pre-Raphaelite collection (Holman Hunt, Rossetti, Ford Madox Brown). Free.", tip: "Two floors, do-able in an hour. The Pre-Raphaelite room is the one." },
  { n: 40, name: "Whitworth",             cat: "daytime",  area: "Oxford Rd, by the park", x: null, y: null, ig: "whitworthart", blurb: "Modern art gallery with a glass extension into Whitworth Park. Café in the trees. Free.", tip: "Combine with a walk through the park. Bit further south, near the uni." },
  { n: 41, name: "Science & Industry Museum", cat: "daytime", area: "Liverpool Rd, Castlefield", x: 15.62, y: 62.61, ig: "scienceandindustrymuseum", blurb: "Set in the world's oldest surviving passenger railway station (1830). Cotton mills, computers, planes, trains. Free.", tip: "Manchester's industrial story in one building. Bigger than it looks." },
  { n: 42, name: "People's History Museum", cat: "daytime", area: "Left Bank, Spinningfields", x: 19.71, y: 48.89, ig: "phmmcr", blurb: "National museum of democracy, working-class history, trade unions, suffrage. The collection of protest banners is genuinely incredible.", tip: "Free. Quietly one of the best museums in the city." },
  { n: 43, name: "National Football Museum", cat: "daytime", area: "Cathedral Gardens", x: 53.97, y: 26.69, ig: "nationalfootballmuseum", blurb: "Hall-of-fame style football museum next to Victoria. Free permanent galleries, paid for some interactives.", tip: "Worth an hour if football's your thing. Skip if not." },
  { n: 44, name: "Imperial War Museum North", cat: "daytime", area: "Salford Quays", x: null, y: null, ig: "imperialwarmuseums", blurb: "Daniel Libeskind building down at Salford Quays. Powerful, properly affecting. Free.", tip: "Tram out to MediaCityUK. Pair with the Lowry next door." }
];

window.MCR_CATEGORIES = [
  { id: "fancy",   label: "Fancy",       sub: "Cocktails, views & doing a bit of pretending.", color: "#E8742C" },
  { id: "modern",  label: "Modern Bars", sub: "Design-led drinking. Cocktails, craft beer & late hours.", color: "#D946A8" },
  { id: "pub",     label: "Old Pubs",    sub: "History, character & proper pints.",            color: "#E8B23A" },
  { id: "dive",    label: "Dive Bars",   sub: "Sticky floors. Late nights. No regrets.",       color: "#B58FE6" },
  { id: "brewery", label: "Breweries",   sub: "Good beer, made in Manchester.",                color: "#4FA8E0" },
  { id: "food",    label: "Food",        sub: "Eat well. Walk it off.",                        color: "#5BB872" },
  { id: "coffee",  label: "Coffee",      sub: "Slow mornings & good pastries.",                color: "#9C7B5A" },
  { id: "music",   label: "Music & Culture", sub: "Gigs, clubs & proper nights out.",          color: "#E84B7C" },
  { id: "culture", label: "NQ Wandering", sub: "Records, shops, murals & getting lost.",       color: "#3CC8B5" },
  { id: "daytime", label: "Daytime",     sub: "Buildings, libraries, museums & galleries — all free unless noted.", color: "#7E8C5A" }
];

window.MCR_NEIGHBOURHOODS = [
  { name: "SALFORD",         x: 18, y: 21.5 },
  { name: "SPINNINGFIELDS",  x: 28, y: 39.5 },
  { name: "CITY CENTRE",     x: 45, y: 36.5 },
  { name: "NORTHERN QUARTER",x: 58, y: 19.5 },
  { name: "ANCOATS",         x: 78, y: 21.5 },
  { name: "PICCADILLY",      x: 68, y: 51.5 },
  { name: "OXFORD ROAD",     x: 38, y: 61.5 },
  { name: "HULME",           x: 30, y: 67.5 },
  { name: "MAYFIELD",        x: 66, y: 61.5 }
];

window.MCR_ITINERARY = [
  { time: "18:00", venue: "Mackie Mayor",     why: "Start in the NQ. Beautiful old market hall, pick from the food stalls, share plates, no decisions." },
  { time: "19:30", venue: "The Castle Hotel", why: "Down to Oldham St for one in a tiny NQ boozer. Robinsons cask, gig room out the back." },
  { time: "21:00", venue: "The Refuge",       why: "Walk south down to Oxford Rd. Huge tiled hotel bar in the old Refuge Assurance building — palms, cocktails, the room does the work. Last civilised stop before it gets messy." },
  { time: "23:15", venue: "Temple Bar",       why: "Walk back up Oxford Rd. Underground, grimy, jukebox, no airs." },
  { time: "00:30", venue: "YES",              why: "Round the corner onto Charles Street. Roof terrace if it’s dry, basement if it’s not. The right way to end it." }
];
